#!/usr/bin/env bash
# This iss the famous FizzBuzz challenge but in shell
for ((i = 1; i < 101; i++)); do
    if [ $((i % 3)) -eq 0 ] && [ $((i % 5)) -eq 0 ]; then
        echo "FizzBuzz"
    elif [ $((i % 3)) -eq 0 ]; then
        echo "Fizz"
    elif [ $((i % 5)) -eq 0 ]; then
        echo "Buzz"
    else
        echo "$i"
    fi
done

