#!/usr/bin/env bash
# The Bash script uses a while loop to read lines from /etc/passwd. It extracts username, 
# user ID, group ID, home directory, shell, and password hash. It then prints this information 
# in a narrative format, incorporating the requested elements.

while IFS=":" read -r username password userid groupid comment homedir shell
do
    echo "The user $username is part of the $groupid gang, lives in $homedir and rides $shell. $userid's place is protected by the passcode $password, more info about the user here: $comment"
done < /etc/passwd
