#!/usr/bin/env bash
# This script prints a string 10 times, printing Hi on the ninth iteration
i=1
while ((i <= 10)); do
    echo "Best School"
    if [ $i == 9 ]; then
        echo "Hi"
    fi
    ((i++))
done
