#!/usr/bin/env bash
# This script prints 10 times, printing bad luck on the forth iteration, good luck on the 8th and best school any other time
i=1
while ((i <= 10)); do
    if [ $i == 4 ]; then
        echo "bad luck"
    elif [ $i == 8 ]; then
        echo "good luck"
    else
        echo "Best School"
    fi
    ((i++))
done
